### ISSUE TITLE
Can't run on macOS

### ISSUE THREAD

**Issue by wuduhren** [Trekky12/kburns-slideshow#2]
`$ python main.py out.mp4 -f example.json`
`
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from slideshow.SlideManager import SlideManager
  File "/Users/eph/Desktop/kburns-slideshow-master/slideshow/SlideManager.py", line 13, in <module>
    from .ImageSlide import ImageSlide
  File "/Users/eph/Desktop/kburns-slideshow-master/slideshow/ImageSlide.py", line 4, in <module>
    from PIL import Image, ExifTags
ImportError: No module named PIL
`

**Comment by Trekky12** [comment]
Hello @wuduhren,

I have no Mac but the error message indicates the missing image processing module PIL. You can install for example Pillow (https://python-pillow.org/) with

`pip install Pillow`

Let me know if this resolves the error.

**Comment by creature** [comment]
FYI I've been playing with this tool on macOS; here's what I did to get it going: 

* Ensure I have `ffmpeg` and `aubio` installed (`brew install ffmpeg aubio`)
* Installed Pillow (`python3.7 pip install pillow`)
    * I'm using Python 3.7, which I _think_ ended up on my system via Homebrew, as macOS ships Python 2.7 by default)
* Ran `main.py` via `python3.7` rather than `python` 
* Updated `config.json` so the `ffmpeg`, `ffprobe`, and `aubio` settings didn't have the `.exe` extension
* Updated line 700 of `slideshow/SlideManager.py`: 

    ```diff
    -            subprocess.call(" ".join(cmd))
    +            subprocess.call(" ".join(cmd), shell=True)
    ```

**Comment by Trekky12** [comment]
Thank you very much @creature. I will include the prerequisites for running the tool on Windows/MacOS to the README
