### ISSUE TITLE
 ffmpeg-video-slideshow-scripts transitions

### ISSUE THREAD

**Issue by JianxiangWang** [Trekky12/kburns-slideshow#3]
Hi, I am a student from China. I have run your code recently and found it really helpful for me. Thank you for your hard and fancy work. Is it possible for sending me the ffmpeg-video-slideshow-scripts transitions for free ( Email: w51141201062@163.com ) ? Thank you very much~

**Comment by Trekky12** [comment]
Hello @JianxiangWang, thank you for your compliment. It's great to hear that the project is helpful for you.
Unfortunately I cannot send you the transitions for free since I would like to honor the hard work of @tanersener with his [ffmpeg-video-slideshow-scripts](https://github.com/tanersener/ffmpeg-video-slideshow-scripts). Addionatlly I had to spend a lot of my time to customize the transitions for this project. 
Thank you for your understanding and I saw that in the meantime you already bought me two coffees for which I would like to thank you very much.
Best regards, 
Trekky12
